name: CI - GameBrary API

on:
  push:
    branches:
      - main
    paths:
      - "src/api/**"
  pull_request:
    paths:
      - "src/api/**"
      - ".github/workflows/ci.yml"

env:

  GO_VERSION: "1.22"

jobs:

  build:

    name: Build API

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:

    - name: Init repository
      uses: actions/checkout@v3

    - name: Obtain Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Get dependencies
      run: go mod tidy

    - name: Build API
      run: go build

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}